print("Hello world")
#len()
lent = len("SIXSEVEN!!!!!!")
print(lent)
# type()
wording = type(True)
print(wording)
# int()
num = int(67)
print(num)
# float()
deci = float(6.7)
print(deci)
# str()
word = str("SIXSEVEN")
print(word)
# max()
Biggest = max(6,7,67)
print(Biggest)
# min()
Smallest = min(6,7,67)
print(Smallest)
# sum()
# range()
# input()
# list
numbers = [1,4,7,4,2,9,6,3,15,6,7]
for i in range(3,15,2):
    print(i)

print(sum(numbers))