name = input('What is your name? ')
reason = input(f'Hi {name}! Do you want to give me a maths question?: ')
first_number = int(input('What is your first number: '))
second_number = int(input('What is your second number: '))
addition = (first_number + second_number)
subtraction = (first_number - second_number)
multiplication = (first_number * second_number)
division = (first_number / second_number)
floor_divison = (first_number // second_number)
exponentiation = (first_number ** second_number)
print(f'The sum of {first_number} and {second_number} is {addition}')
print(f'The difference of {first_number} and {second_number} is {subtraction}')
print(f'The product of {first_number} and {second_number} is {multiplication}')
print(f'The quotient of {first_number} and {second_number} is {division}')
print(f'The floor division of {first_number} and {second_number} is {floor_divison}')
print(f'The exponentatial of {first_number} and {second_number} is {exponentiation}')